### ISSUE TITLE
Click validation errors

### ISSUE THREAD

**Issue by SiCoe** [SiCoe/what3words.resolver.server#1]
Running the "Build and validate click package" from the Ubuntu SDK shows the following error

```
Error: Traceback (most recent call last):
  File "/usr/bin/click-review", line 162, in <module>
    main()
  File "/usr/bin/click-review", line 156, in main
    results.run_all_checks(overrides)
  File "/usr/bin/click-review", line 105, in run_all_checks
    section = self._run_module_checks(module, overrides)
  File "/usr/bin/click-review", line 97, in _run_module_checks
    review.do_checks()
  File "/usr/lib/python3/dist-packages/clickreviews/common.py", line 384, in do_checks
    func()
  File "/usr/lib/python3/dist-packages/clickreviews/cr_security.py", line 691, in check_policy_groups
    if len(policy_groups) < 1:
TypeError: object of type 'NoneType' has no len()

Traceback (most recent call last):
  File "/usr/bin/click-review", line 162, in <module>
    main()
  File "/usr/bin/click-review", line 156, in main
    results.run_all_checks(overrides)
  File "/usr/bin/click-review", line 105, in run_all_checks
    section = self._run_module_checks(module, overrides)
  File "/usr/bin/click-review", line 97, in _run_module_checks
    review.do_checks()
  File "/usr/lib/python3/dist-packages/clickreviews/common.py", line 384, in do_checks
    func()
  File "/usr/lib/python3/dist-packages/clickreviews/cr_security.py", line 691, in check_policy_groups
    if len(policy_groups) < 1:
TypeError: object of type 'NoneType' has no len()
Command failed
```

**Comment by SiCoe** [comment]
should be assigned to [what3words.resolver](https://github.com/SiCoe/what3words.resolver)
